version: '3'

services:
  doc_cicd_pine_nginx:
    container_name: doc_cicd_pine_nginx
    image: nginx:stable
    ports:
      - "80"
    volumes:
      - ./doc_cicd_pine:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - doc_cicd_pine_db
      - doc_cicd_pine_php 
    network_mode: "rev-proxy"
    environment:
      - VIRTUAL_HOST=cicd.kataho.app
      - LETSENCRYPT_HOST=cicd.kataho.app
  doc_cicd_pine_php:
    container_name: doc_cicd_pine_php
    build: ./php
    links:
      - doc_cicd_pine_db
    volumes:
      - ./doc_cicd_pine:/var/www/html
    networks:
      - default
    
  doc_cicd_pine_db:
    container_name: doc_cicd_pine_db
    image: mysql:5.7.30
    ports:
      - "7676:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $USER
      MYSQL_PASSWORD: $USER_PASSWORD
      MYSQL_HOST: doc_cicd_pine_db
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - default
  
  doc_cicd_pine_pma:
    container_name: doc_cicd_pine_pma
    image: phpmyadmin/phpmyadmin
    links:
      - doc_cicd_pine_db:db
    ports:
      - "8686:80"
    environment:
      UPLOAD_LIMIT: 2000M
      PMA_HOST: doc_cicd_pine_db
      MYSQL_USER: $USER
      MYSQL_PASSWORD: $USER_PASSWORD
      MYSQL_ROOT_PASSWORD: $ROOT_PASSWORD
    
volumes:
  doc_cicd_pine:
  db:
  

networks:
  default:
    external: 
      name: rev-proxy

